### ISSUE TITLE
Options for whether to download the Adventures, Scenarios etc.

### ISSUE THREAD

**Issue by tobeyStraitjacket** [CuriousNekomimi/AIDungeonRescue#1]
toebean here :)

I've had users who wanted to download just their scenarios as they had 1000+ adventures and they didn't care about them, but they cared about their scenarios, so I edited the original to take into account this option.

It looks like your edit is of the original script without these options, so I figured I'll give you a heads up that it might be nice to incorporate those options again. It's a real simple mod I made of the original but I figured I'd upload it for you anyway: [downloadscenarios_updated.zip](https://github.com/CuriousNekomimi/AIDungeonRescue/files/6412051/downloadscenarios_updated.zip)

Just involved adding a standard function for yes/no questions, and simply asking the user up front which ones they want before beginning downloading anything.

```py
def yes_or_no(question):
    while "the answer is invalid":
        reply = str(input(question+' (y/n): ')).lower().strip()
        if reply[0] == 'y':
            return True
        if reply[0] == 'n':
            return False
```

```py
download_stories = yes_or_no('Download stories (adventures)?')
download_scenarios = yes_or_no('Download scenarios?')
```

```py
if (download_stories):
```
... code that downloads the stories/adventures goes here ...
```py
else:
    print('Skipping stories...')
```

etc.

**Comment by CuriousNekomimi** [comment]
Thank you for the suggestion. I've added options to skip each type of download. Resolved.
